[package]
name = "idx_binary"
version = "0.6.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed string file. It uses mmap , strings_set_file and avltiree."

repository = "https://github.com/OdenShirataki/idx_binary"

keywords = ["index","file","avltree","memmap","database"]
categories = ["algorithms","caching","filesystem"]
license = "MIT/Apache-2.0"

[dependencies]
various_data_file="0.4"
idx_sized="0.12"
