[package]
name = "indexed_string_file"
version = "0.4.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed string file. It uses mmap , strings_set_file and tri-avltree."

repository = "https://github.com/OdenShirataki/indexed_data_file"

keywords = ["index","file","avltree","memmap","database"]
license = "MIT"

[dependencies]
libc="0.2"
indexed_data_file={ path="../indexed_data_file" , version="0.4" }
strings_set_file={ path="../strings_set_file" , version="0.1" }