[package]
name = "idx_binary"
version = "0.2.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed string file. It uses mmap , strings_set_file and avltiree."

repository = "https://github.com/OdenShirataki/idx_binary"

keywords = ["index","file","avltree","memmap","database"]
license = "MIT/Apache-2.0"

[dependencies]
libc="0.2"
idx_sized={ path="../idx_sized" , version="0.8" }
various_data_file={ path="../various_data_file" , version="0.2" }